version: '3.7'

services:

  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  post-character:
    build:
      context: ./API/services/postCharacter
      dockerfile: Dockerfile.dev
    volumes:
      - ./API/services/postCharacter:/usr/src/app
      - /usr/src/app/node_modules
  get-character:
    build:
      context: ./API/services/getCharacter
      dockerfile: Dockerfile.dev
    volumes:
      - ./API/services/getCharacter:/usr/src/app
      - /usr/src/app/node_modules
  gateway-character:
    build:
      context: ./API/services/gateway
      dockerfile: Dockerfile.dev
    volumes:
      - ./API/services/gateway:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3005:3005"


volumes:
  elasticsearch-data:
    driver: local
